services:
  app:
    container_name: astro-demo-app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - type: bind
        source: ../
        target: /workspaces/astro-demo/
    tty: true
